In [29]:
import copy
import csv
from pathlib import Path

import pandas as pd
import numpy as np

In [52]:
with open("gold-data-en.txt", "r") as f_in:
    gold_data = f_in.read().split("\n")

gold_data

['attack_nn',
 'bag_nn',
 'ball_nn',
 'bit_nn',
 'chairman_nn',
 'circle_vb',
 'contemplation_nn',
 'donkey_nn',
 'edge_nn',
 'face_nn',
 'fiction_nn',
 'gas_nn',
 'graft_nn',
 'head_nn',
 'land_nn',
 'lane_nn',
 'lass_nn',
 'multitude_nn',
 'ounce_nn',
 'part_nn',
 'pin_vb',
 'plane_nn',
 'player_nn',
 'prop_nn',
 'quilt_nn',
 'rag_nn',
 'record_nn',
 'relationship_nn',
 'risk_nn',
 'savage_nn',
 'stab_nn',
 'stroke_vb',
 'thump_nn',
 'tip_vb',
 'tree_nn',
 'twist_nn',
 'word_nn']

In [53]:
input_dataset = pd.read_json("inputs_en.data")
print(input_dataset.shape)
# full_dataset.rename(columns={"lemma": "word"}, inplace=True)
input_dataset.drop(columns=["start1", "end1", "start2", "end2"], inplace=True)
input_dataset.head()

(898312, 9)

,id,lemma,pos,sentence1,sentence2
0,dev.graft_nn.0,graft_nn,NOUN,A maiden plant (a tree but one year from the g...,"Fine mould or peat, from the box in which the ..."
1,dev.graft_nn.1,graft_nn,NOUN,A maiden plant (a tree but one year from the g...,"For the same reason, root-grafting the pear is..."
2,dev.graft_nn.2,graft_nn,NOUN,A maiden plant (a tree but one year from the g...,Grafts often bear some fine clusters the first...
3,dev.graft_nn.3,graft_nn,NOUN,A maiden plant (a tree but one year from the g...,"In all cases success is more certain, when the..."
4,dev.graft_nn.4,graft_nn,NOUN,A maiden plant (a tree but one year from the g...,""" Mr. STOMS asks: ' Why graft on the quince st..."

In [54]:
cont = 0
words_annotated = []

for d in Path("en_mcl/").rglob("*.scores"):
    word = d.stem.split(".")[1]
    if word in gold_data:
        words_annotated.append(pd.read_json(d))

annotations = pd.concat(words_annotated)
print(annotations.head())
print(annotations.shape)

                   id                     score
0  dev.stab_nn.117266  [0.46295887, 0.46200073]
1  dev.stab_nn.117267  [0.49659023, 0.46464413]
2  dev.stab_nn.117268   [0.4628612, 0.46263146]
3  dev.stab_nn.117269  [0.46715596, 0.46572125]
4  dev.stab_nn.117270   [0.5142891, 0.48653802]
(732602, 2)

In [55]:
full_dataset = pd.merge(annotations, input_dataset)
print(full_dataset.shape)
full_dataset.rename(
    columns={"lemma": "word"},
    inplace=True,
)
full_dataset.drop(columns=["pos"], inplace=True)
full_dataset.head()

(732602, 6)

,id,score,word,sentence1,sentence2
0,dev.stab_nn.117266,"[0.46295887, 0.46200073]",stab_nn,His long finger made swift stabs here and ther...,despair by making them feel too deeply the pov...
1,dev.stab_nn.117267,"[0.49659023, 0.46464413]",stab_nn,His long finger made swift stabs here and ther...,"I don't deny that there was a pang in it, yes,..."
2,dev.stab_nn.117268,"[0.4628612, 0.46263146]",stab_nn,His long finger made swift stabs here and ther...,"* * * * And yet, melancholy to relate, we find..."
3,dev.stab_nn.117269,"[0.46715596, 0.46572125]",stab_nn,His long finger made swift stabs here and ther...,the rashness to bethink them of a tour among t...
4,dev.stab_nn.117270,"[0.5142891, 0.48653802]",stab_nn,His long finger made swift stabs here and ther...,"An arrow shot from a ravine, a stab given in t..."

In [56]:
full_dataset["score"] = full_dataset["score"].apply(
    lambda x: np.mean([float(v) for v in x])
)

full_dataset.head()

,id,score,word,sentence1,sentence2
0,dev.stab_nn.117266,0.462480,stab_nn,His long finger made swift stabs here and ther...,despair by making them feel too deeply the pov...
1,dev.stab_nn.117267,0.480617,stab_nn,His long finger made swift stabs here and ther...,"I don't deny that there was a pang in it, yes,..."
2,dev.stab_nn.117268,0.462746,stab_nn,His long finger made swift stabs here and ther...,"* * * * And yet, melancholy to relate, we find..."
3,dev.stab_nn.117269,0.466439,stab_nn,His long finger made swift stabs here and ther...,the rashness to bethink them of a tour among t...
4,dev.stab_nn.117270,0.500414,stab_nn,His long finger made swift stabs here and ther...,"An arrow shot from a ravine, a stab given in t..."

In [57]:
gold_words_annotated = []
cont = 0

for d in Path("dwug_en/data").rglob("*judgments.csv"):
    cad = str(d)
    word = cad.split("/")[-2]

    if word in gold_data:
        data = pd.read_csv(d, sep="\t")
        data_cleaned = data[data["judgment"] != 0.0]

        gold_words_annotated.append(copy.deepcopy(data_cleaned))

In [58]:
gold_data_annotated = pd.concat(gold_words_annotated)
gold_data_annotated.shape
gold_data_annotated.rename(columns={"lemma": "word"}, inplace=True)
gold_data_annotated.drop(columns=["annotator"], inplace=True)

In [59]:
print(gold_data_annotated.shape)
gold_data_annotated.head()

(37181, 6)

,identifier1,identifier2,judgment,comment,word,round
0,nf_1850_747863.txt-354-23,news_1970_728573.txt-4-21,1.0,,graft_nn,3
1,nf_1997_773614.txt-323-12,mag_1977_431930.txt-27-6,1.0,,graft_nn,3
2,nf_1858_747890.txt-616-0,mag_1979_480051.txt-9-19,1.0,,graft_nn,3
3,news_1963_723197.txt-45-12,news_1962_722583.txt-15-13,4.0,,graft_nn,3
4,fic_1994_54058.txt-385-6,mag_1999_407759.txt-31-27,3.0,,graft_nn,3

In [60]:
gold_data_annotated["_key"] = gold_data_annotated.apply(
    lambda row: tuple(sorted([row["identifier1"], row["identifier2"]])), axis=1
)
gold_data_annotated = gold_data_annotated.drop_duplicates(subset="_key").drop(
    columns="_key"
)
print(gold_data_annotated.shape)
gold_data_annotated.head()

(23233, 6)

,identifier1,identifier2,judgment,comment,word,round
0,nf_1850_747863.txt-354-23,news_1970_728573.txt-4-21,1.0,,graft_nn,3
1,nf_1997_773614.txt-323-12,mag_1977_431930.txt-27-6,1.0,,graft_nn,3
2,nf_1858_747890.txt-616-0,mag_1979_480051.txt-9-19,1.0,,graft_nn,3
3,news_1963_723197.txt-45-12,news_1962_722583.txt-15-13,4.0,,graft_nn,3
4,fic_1994_54058.txt-385-6,mag_1999_407759.txt-31-27,3.0,,graft_nn,3

In [61]:
sentences_with_ids_gold_data = []
cont = 0

for d in Path("dwug_en/data").rglob("*uses.csv"):
    cad = str(d)
    word = cad.split("/")[-2]

    if word in gold_data:
        cont += 1
        data = pd.read_csv(
            d,
            sep="\t",
            engine="python",
            quoting=csv.QUOTE_NONE,
        )
        sentences_with_ids_gold_data.append(copy.deepcopy(data))

print(cont)

37

In [62]:
sentences_gold_data = pd.concat(sentences_with_ids_gold_data)
print(sentences_gold_data.shape)
sentences_gold_data.drop(
    columns=[
        "indexes_target_token",
        "indexes_target_sentence",
        "indexes_target_token_tokenized",
        "indexes_target_sentence_tokenized",
        "context_lemmatized",
        "context_pos",
        "context_tokenized",
        "pos",
        "date",
        "description",
    ],
    inplace=True,
)
sentences_gold_data.rename(columns={"lemma": "word"}, inplace=True)
sentences_gold_data.head()

(7381, 14)

,word,grouping,identifier,context
0,graft_nn,1,nf_1845_747928.txt-634-11,A maiden plant (a tree but one year from the g...
1,graft_nn,1,nf_1844_747892.txt-595-18,When the operation is performed close to the g...
2,graft_nn,1,nf_1850_747863.txt-1739-22,"Fine mould or peat, from the box in which the ..."
3,graft_nn,1,nf_1850_747863.txt-3421-26,"For the same reason, root-grafting the pear is..."
4,graft_nn,1,nf_1839_747931.txt-374-35,"In the following spring, the grafted trees may..."

In [63]:
result = pd.merge(
    gold_data_annotated,
    sentences_gold_data[["identifier", "context"]],
    left_on="identifier1",
    right_on="identifier",
    how="left",
)

result = result.rename(columns={"context": "sentence1"}).drop(columns="identifier")
result.head()

,identifier1,identifier2,judgment,comment,word,round,sentence1
0,nf_1850_747863.txt-354-23,news_1970_728573.txt-4-21,1.0,,graft_nn,3,19 shows a stock cut off for cleft-grafting wi...
1,nf_1997_773614.txt-323-12,mag_1977_431930.txt-27-6,1.0,,graft_nn,3,"The work, he acknowledged to Reynolds, was "" a..."
2,nf_1858_747890.txt-616-0,mag_1979_480051.txt-9-19,1.0,,graft_nn,3,Grafts taken - from the upright shoots near th...
3,news_1963_723197.txt-45-12,news_1962_722583.txt-15-13,4.0,,graft_nn,3,"How about elimination of largescale waste and,..."
4,fic_1994_54058.txt-385-6,mag_1999_407759.txt-31-27,3.0,,graft_nn,3,"Sarah touched the edge of the graft, a bit of ..."

In [64]:
result = pd.merge(
    result,
    sentences_gold_data[["identifier", "context"]],
    left_on="identifier2",
    right_on="identifier",
    how="left",
)
result = result.rename(columns={"context": "sentence2"}).drop(columns=["identifier", "comment"])
result.head()

,identifier1,identifier2,judgment,word,round,sentence1,sentence2
0,nf_1850_747863.txt-354-23,news_1970_728573.txt-4-21,1.0,graft_nn,3,19 shows a stock cut off for cleft-grafting wi...,The names of policemen who discussed corruptio...
1,nf_1997_773614.txt-323-12,mag_1977_431930.txt-27-6,1.0,graft_nn,3,"The work, he acknowledged to Reynolds, was "" a...",They present me with evidence of graft in Wash...
2,nf_1858_747890.txt-616-0,mag_1979_480051.txt-9-19,1.0,graft_nn,3,Grafts taken - from the upright shoots near th...,: they support Stroessner for what they can ge...
3,news_1963_723197.txt-45-12,news_1962_722583.txt-15-13,4.0,graft_nn,3,"How about elimination of largescale waste and,...","The politicians are dormant, they'll do nothin..."
4,fic_1994_54058.txt-385-6,mag_1999_407759.txt-31-27,3.0,graft_nn,3,"Sarah touched the edge of the graft, a bit of ...","Dr. Orentreich, whose father Dr. Norman Orentr..."

In [66]:
result.shape

(23233, 7)

In [38]:
result_full_dataset = pd.merge(
    result,
    full_dataset,
    on=["word", "sentence1", "sentence2"],
    how="left",
)
result_full_dataset = result_full_dataset[
    [
        "identifier1",
        "sentence1",
        "identifier2",
        "sentence2",
        "word",
        "score",
        "judgment",
    ]
]
print(result_full_dataset.shape)
result_full_dataset.head()

(23520, 7)

,identifier1,sentence1,identifier2,sentence2,word,score,judgment
0,nf_1850_747863.txt-354-23,19 shows a stock cut off for cleft-grafting wi...,news_1970_728573.txt-4-21,The names of policemen who discussed corruptio...,graft_nn,NaN,1.0
1,nf_1997_773614.txt-323-12,"The work, he acknowledged to Reynolds, was "" a...",mag_1977_431930.txt-27-6,They present me with evidence of graft in Wash...,graft_nn,NaN,1.0
2,nf_1858_747890.txt-616-0,Grafts taken - from the upright shoots near th...,mag_1979_480051.txt-9-19,: they support Stroessner for what they can ge...,graft_nn,NaN,1.0
3,news_1963_723197.txt-45-12,"How about elimination of largescale waste and,...",news_1962_722583.txt-15-13,"The politicians are dormant, they'll do nothin...",graft_nn,NaN,4.0
4,fic_1994_54058.txt-385-6,"Sarah touched the edge of the graft, a bit of ...",mag_1999_407759.txt-31-27,"Dr. Orentreich, whose father Dr. Norman Orentr...",graft_nn,0.542805,3.0

In [39]:
result_full_dataset["pair_key"] = result_full_dataset.apply(
    lambda row: tuple(sorted([row["identifier1"], row["identifier2"]])), axis=1
)
result_full_dataset = result_full_dataset.drop_duplicates(subset=["word", "sentence1", "sentence2"])
result_full_dataset = result_full_dataset.drop_duplicates(subset=["pair_key"])
result_full_dataset.drop(columns=["pair_key", "judgment"], inplace=True)
result_full_dataset.rename(columns={"score": "prediction"}, inplace=True)
print(result_full_dataset.shape)
result_full_dataset.head()

(23210, 6)

,identifier1,sentence1,identifier2,sentence2,word,prediction
0,nf_1850_747863.txt-354-23,19 shows a stock cut off for cleft-grafting wi...,news_1970_728573.txt-4-21,The names of policemen who discussed corruptio...,graft_nn,NaN
1,nf_1997_773614.txt-323-12,"The work, he acknowledged to Reynolds, was "" a...",mag_1977_431930.txt-27-6,They present me with evidence of graft in Wash...,graft_nn,NaN
2,nf_1858_747890.txt-616-0,Grafts taken - from the upright shoots near th...,mag_1979_480051.txt-9-19,: they support Stroessner for what they can ge...,graft_nn,NaN
3,news_1963_723197.txt-45-12,"How about elimination of largescale waste and,...",news_1962_722583.txt-15-13,"The politicians are dormant, they'll do nothin...",graft_nn,NaN
4,fic_1994_54058.txt-385-6,"Sarah touched the edge of the graft, a bit of ...",mag_1999_407759.txt-31-27,"Dr. Orentreich, whose father Dr. Norman Orentr...",graft_nn,0.542805

In [40]:
result_full_dataset.dropna(inplace=True)
result_full_dataset.shape

(11746, 6)

In [36]:
result_full_dataset.to_csv(
    "deepmistake_model_es.csv",
    index=False,
)